
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Copyright (C) 2015 diTerminal Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 *
 * @author diTerminal Team
 */
public class MisiEkstra extends javax.swing.JFrame {

    /**
     * Creates new form MisiEkstra
     */
    public MisiEkstra() {
        initComponents();
        
        // Center Window
        setLocationRelativeTo(null);
        
        // Image Icon
        setIconImage(new ImageIcon(getClass().getResource("/img/PremanTerminalLogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        btLinux = new javax.swing.JButton();
        btKernel = new javax.swing.JButton();
        btGNU = new javax.swing.JButton();
        btRepositori = new javax.swing.JButton();
        btFreeSoftware = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("diTerminal - Misi 3");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MISI EKSTRA diTerminal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btBack.setBackground(new java.awt.Color(51, 51, 51));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btBack.setToolTipText("Kembali");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btHome.setBackground(new java.awt.Color(51, 51, 51));
        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btHome.setToolTipText("Rumah");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        btLinux.setBackground(new java.awt.Color(51, 51, 51));
        btLinux.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btLinux.setForeground(new java.awt.Color(255, 255, 255));
        btLinux.setText("LINUX");
        btLinux.setToolTipText("Linux");
        btLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLinuxActionPerformed(evt);
            }
        });

        btKernel.setBackground(new java.awt.Color(51, 51, 51));
        btKernel.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btKernel.setForeground(new java.awt.Color(255, 255, 255));
        btKernel.setText("KERNEL");
        btKernel.setToolTipText("Kernel");
        btKernel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKernelActionPerformed(evt);
            }
        });

        btGNU.setBackground(new java.awt.Color(51, 51, 51));
        btGNU.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btGNU.setForeground(new java.awt.Color(255, 255, 255));
        btGNU.setText("GNU");
        btGNU.setToolTipText("GNU");
        btGNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGNUActionPerformed(evt);
            }
        });

        btRepositori.setBackground(new java.awt.Color(51, 51, 51));
        btRepositori.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btRepositori.setForeground(new java.awt.Color(255, 255, 255));
        btRepositori.setText("REPOSITORI");
        btRepositori.setToolTipText("Repositori");
        btRepositori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRepositoriActionPerformed(evt);
            }
        });

        btFreeSoftware.setBackground(new java.awt.Color(51, 51, 51));
        btFreeSoftware.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btFreeSoftware.setForeground(new java.awt.Color(255, 255, 255));
        btFreeSoftware.setText("FREE SOFTWARE");
        btFreeSoftware.setToolTipText("Free Software");
        btFreeSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFreeSoftwareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btGNU, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btHome)))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btKernel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRepositori, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btFreeSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGNU, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btFreeSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKernel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRepositori, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        // kembali ke MainMenu
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        // kembali ke Main Frame
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_btHomeActionPerformed

    private void btLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLinuxActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "LINUX akan tersedia di versi alpha 0.2",
                "LINUX",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btLinuxActionPerformed

    private void btGNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGNUActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "GNU akan tersedia di versi alpha 0.2",
                "GNU",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btGNUActionPerformed

    private void btFreeSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFreeSoftwareActionPerformed
        // TODO add your handling code here
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "Free Software akan tersedia di versi alpha 0.2",
                "Free Software",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btFreeSoftwareActionPerformed

    private void btKernelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKernelActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "Kernel akan tersedia di versi alpha 0.2",
                "Kernel",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btKernelActionPerformed

    private void btRepositoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRepositoriActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "Repositori akan tersedia di versi alpha 0.2",
                "Repositori",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btRepositoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Misi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Misi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Misi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Misi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisiEkstra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btFreeSoftware;
    private javax.swing.JButton btGNU;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btKernel;
    private javax.swing.JButton btLinux;
    private javax.swing.JButton btRepositori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
