
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Copyright (C) 2015 diTerminal Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 *
 * @author diTerminal Team
 */
public class Misi1 extends javax.swing.JFrame {

    /**
     * Creates new form Misi1
     */
    public Misi1() {
        initComponents();
        
        // Center Window
        setLocationRelativeTo(null);
        
        // Image Icon
        setIconImage(new ImageIcon(getClass().getResource("/img/PremanTerminalLogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbJudulMisi1 = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        btPraktikum1 = new javax.swing.JButton();
        btPraktikum2 = new javax.swing.JButton();
        btPraktikum3 = new javax.swing.JButton();
        btPraktikum4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("diTerminal - Misi 1");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 113, 224));

        lbJudulMisi1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lbJudulMisi1.setForeground(new java.awt.Color(255, 255, 255));
        lbJudulMisi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJudulMisi1.setText("Misi diTerminal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lbJudulMisi1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbJudulMisi1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        btBack.setBackground(new java.awt.Color(51, 51, 51));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btBack.setToolTipText("Kembali");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btHome.setBackground(new java.awt.Color(51, 51, 51));
        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btHome.setToolTipText("Rumah");
        btHome.setBorderPainted(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        btPraktikum1.setBackground(new java.awt.Color(50, 113, 224));
        btPraktikum1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btPraktikum1.setForeground(new java.awt.Color(255, 255, 255));
        btPraktikum1.setText("MISI PRAKTIKUM 1");
        btPraktikum1.setToolTipText("Praktikum 1");
        btPraktikum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPraktikum1ActionPerformed(evt);
            }
        });

        btPraktikum2.setBackground(new java.awt.Color(50, 113, 224));
        btPraktikum2.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btPraktikum2.setForeground(new java.awt.Color(255, 255, 255));
        btPraktikum2.setText("MISI PRAKTIKUM 2");
        btPraktikum2.setToolTipText("Praktikum 2");
        btPraktikum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPraktikum2ActionPerformed(evt);
            }
        });

        btPraktikum3.setBackground(new java.awt.Color(50, 113, 224));
        btPraktikum3.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btPraktikum3.setForeground(new java.awt.Color(255, 255, 255));
        btPraktikum3.setText("MISI PRAKTIKUM 3");
        btPraktikum3.setToolTipText("Praktikum 3");
        btPraktikum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPraktikum3ActionPerformed(evt);
            }
        });

        btPraktikum4.setBackground(new java.awt.Color(50, 113, 224));
        btPraktikum4.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btPraktikum4.setForeground(new java.awt.Color(255, 255, 255));
        btPraktikum4.setText("MISI PRAKTIKUM 4");
        btPraktikum4.setToolTipText("Praktikum 4");
        btPraktikum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPraktikum4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPraktikum1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(btPraktikum3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPraktikum2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(btPraktikum4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPraktikum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPraktikum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPraktikum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPraktikum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        // kembali ke MainMenu
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        // kembali ke Main Frame
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_btHomeActionPerformed

    private void btPraktikum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPraktikum1ActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "MISI PRAKTIKUM 1 akan tersedia di versi alpha 0.2",
                "MISI PRAKTIKUM 1",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btPraktikum1ActionPerformed

    private void btPraktikum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPraktikum2ActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "MISI PRAKTIKUM 2 akan tersedia di versi alpha 0.2",
                "MISI PRAKTIKUM 2",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btPraktikum2ActionPerformed

    private void btPraktikum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPraktikum3ActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "MISI PRAKTIKUM 3 akan tersedia di versi alpha 0.2",
                "MISI PRAKTIKUM 3",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btPraktikum3ActionPerformed

    private void btPraktikum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPraktikum4ActionPerformed
        // TODO add your handling code here:
        // Informasi fitur
        JOptionPane.showMessageDialog(
                rootPane,
                "MISI PRAKTIKUM 4 akan tersedia di versi alpha 0.2",
                "MISI PRAKTIKUM 4",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btPraktikum4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Misi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Misi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Misi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Misi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Misi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btPraktikum1;
    private javax.swing.JButton btPraktikum2;
    private javax.swing.JButton btPraktikum3;
    private javax.swing.JButton btPraktikum4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbJudulMisi1;
    // End of variables declaration//GEN-END:variables
}
