
import javax.swing.ImageIcon;

/*
 * Copyright (C) 2015 diTerminal Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 *
 * @author diTerminal Team
 */
public class Tentang extends javax.swing.JFrame {

    /**
     * Creates new form Tentang
     */
    public Tentang() {
        initComponents();
        
        // Center Window
        setLocationRelativeTo(null);
        
        // Image Icon
        setIconImage(new ImageIcon(getClass().getResource("/img/PremanTerminalLogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogoAplikasi = new javax.swing.JLabel();
        lbJudulAplikasi = new javax.swing.JLabel();
        lbSubJudulAplikasi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbVersi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btContact = new javax.swing.JButton();
        lbgithub = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tentang diTerminal");
        setBackground(java.awt.Color.white);
        setResizable(false);

        imgLogoAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogoAplikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PremanTerminalLogo64.png"))); // NOI18N

        lbJudulAplikasi.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lbJudulAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJudulAplikasi.setText("diTerminal"); // NOI18N

        lbSubJudulAplikasi.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbSubJudulAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubJudulAplikasi.setText("Aplikasi Belajar Command Line Sistem Operasi Berbasis Linux"); // NOI18N

        lbVersi.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbVersi.setText("Versi Alpha 0.1.5"); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextPane1.setText("\"diTerminal\" adalah aplikasi yang ditujukan untuk media belajar bagi pengguna Linux pemula yang ingin belajar tentang dasar dari Command Line, dan Sistem Operasi Linux.\n\nAplikasi ini pada dasarnya terinspirasi dari Aplikasi \"Otodidak\" karya Ade Malsasa Akbar yang sama-sama memiliki prinsip click n run, dan Materi yang kami developer dapatkan pada saat kuliah tentang sistem operasi.\n\nNama \"diTerminal\" dipilih dari nama asli aplikasi terminal atau tampilan command line pada sistem operasi berbasis Linux atau Unix-Like itu seperti CMD pada sistem operasi Microsoft Windows, dan penambahan \"di\" sebagai penunjuk bahwa materi yang ada akan lebih sering digunakan di program bernama Terminal. Penulisan \"di\" dan \"Terminal\" sengaja tidak dipisah karena tidak menunjuk tempat.\n\n\"diTerminal\" Bebas dan Open Source. Siapapun dapat memperbanyak, memodifikasi tanpa ijin. Namun, diharapkan untuk tidak memodifikasi \"diTerminal\" menjadi aplikasi yang buruk, atau menjual Aplikasi \"diTerminal\" ini tanpa ijin dari developer \"diTerminal\".\n\n\"diTerminal\" akan hadir dalam 3 platform yaitu Linux (.jar), Windows (.exe), dan Android."); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        btContact.setBackground(new java.awt.Color(50, 113, 224));
        btContact.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btContact.setForeground(new java.awt.Color(255, 255, 255));
        btContact.setText("Hubungi Developer");
        btContact.setToolTipText("Developer");
        btContact.setBorder(null);
        btContact.setBorderPainted(false);
        btContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContactActionPerformed(evt);
            }
        });

        lbgithub.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbgithub.setText("<html><a href=\"https://github.com/diTerminal/diTerminal\">https://github.com/diTerminal/diTerminal</a></html>"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLogoAplikasi, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbJudulAplikasi, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbSubJudulAplikasi, javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lbVersi)
                                .addComponent(lbgithub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btContact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogoAplikasi)
                .addGap(18, 18, 18)
                .addComponent(lbJudulAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSubJudulAplikasi)
                .addGap(4, 4, 4)
                .addComponent(lbVersi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbgithub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btContact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContactActionPerformed
        // TODO add your handling code here:
        // Panggil window HubungiDeveloper
        new HubungiDeveloper().setVisible(true);
    }//GEN-LAST:event_btContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tentang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContact;
    private javax.swing.JLabel imgLogoAplikasi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbJudulAplikasi;
    private javax.swing.JLabel lbSubJudulAplikasi;
    private javax.swing.JLabel lbVersi;
    private javax.swing.JLabel lbgithub;
    // End of variables declaration//GEN-END:variables
}
